apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: iam-ingress-route-websecure
  namespace: skillometer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`iam.skillometer.idev-present.com`)
      kind: Rule
      services:
        - name: casdoor
          port: 8000