@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class alembic_version {
   version_num: varchar(32)
}
class applicant_xp {
   applicant_id: varchar(50)
   company_name: varchar
   company_id: varchar
   position: varchar
   position_id: varchar
   start_date: timestamp
   end_date: timestamp
   description: varchar
   skill_set: varchar
   id: varchar
}
class applicants {
   user_id: varchar(50)
   title: varchar
   salary_from: integer
   currency: varchar(50)
   age: integer
   experience: varchar
   is_relocation: boolean
   is_remote: boolean
   last_visited: timestamp
   registered_at: timestamp
   search_status_id: varchar(50)
   qualification_id: varchar(50)
   division_id: varchar(50)
   city_id: varchar(50)
   skill_set: varchar
   id: varchar
}
class companies {
   title: varchar
   subtitle: varchar
   href: varchar
   logo_url: varchar
   accredited: boolean
   habr_id: varchar
   id: varchar
}
class dict_city {
   name: varchar(50)
   fias_id: varchar(50)
   habr_id: integer
   habr_alias: varchar(50)
   country_name: varchar(50)
   region_name: varchar(50)
   id: varchar(50)
}
class dict_division {
   name: varchar(50)
   habr_id: integer
   id: varchar(50)
}
class dict_employment_type {
   name: varchar(50)
   habr_id: varchar(50)
   hh_id: varchar(50)
   id: varchar(50)
}
class dict_qualification {
   name: varchar(50)
   habr_id: integer
   id: varchar(50)
}
class dict_search_status {
   name: varchar(50)
   habr_id: integer
   id: varchar(50)
}
class dict_skill {
   name: varchar(50)
   type: varchar(50)
   qualification_id: varchar(50)
   division_id: varchar(50)
   habr_id: integer
   id: varchar(50)
}
class vacancies {
   habr_id: integer
   hh_id: integer
   url: varchar
   salary_from: integer
   salary_to: integer
   currency: varchar
   is_remote: boolean
   description: varchar
   team: varchar
   todo: varchar
   city_id: varchar
   employment_type_id: varchar
   division_id: varchar
   qualification_id: varchar
   created_at: timestamp
   published_at: timestamp
   owner_id: varchar
   company_id: varchar
   skill_set: varchar
   name: varchar
   id: varchar
}
class reply {
    id: uuid
    vacancy_id: varchar
    applicant_id: varchar
    status: varchar
    owner_id: uuid
    updated_at: datetime
    updated_by: varchar
    applicant_avatar: varchar
    applicant_fullname: varchar
    applicant_phone: varchar
    applicant_telegram: varchar
    applicant_email: varchar
}

class reply_comments {
    id: uuid
    author_id: uuid
    author_name: varchar
    reply_id: uuid
    content: varchar
    created_at: datetime
}

applicant_xp          -[#595959,plain]-^  applicants           : "applicant_id:id"
applicant_xp          -[#595959,plain]-^  companies            : "company_id:id"
vacancies             -[#595959,plain]-^  companies            : "company_id:id"
@enduml
