@startuml

|Подбор соискателя|
:Подбор соискателя;
note right: начало процесса

-> Лид принят в обработку;
note right: стаж по умолчанию

|Интервью|
:Назначение интервью;
note left: расписание
:Проведение интервью;
:Заполнение формы;

if (Результат?) then (Положительный)
    :Перевод на стадию собеседования;
else (Отрицательный)
    :Отказ соискателю;
    note left: причина отказа
endif;

|Собеседование|
:Проведение собеседования;
:Оценка соискателя;

if (Результат собеседования?) then (Положительный)
    :Выдача технического задания;
else (Отрицательный)
    :Отказ соискателю;
    note right: причина отказа
endif;

|Техническое задание|
:Выполнение технического задания;
:Оценка технической работы;

if (Результат ТЗ?) then (Положительный)
    :Предложение работы;
else (Отрицательный)
    :Отказ соискателю;
    note left: причина отказа
endif;

:Конец процесса;
@enduml