@startuml
!define RECTANGLE activity
title Диаграмма активности для системы по работе с соискателями

start
:Подбор Соискателя;
-> Подбор;
if (Кандидат найден?) then (да)
    :Проверка резюме;
    -> Интервью;
else (нет)
    -> Подбор;
endif

:Интервью;
if (Интервью проведено?) then (да)
    if (Положительный результат?) then (да)
        -> Собеседование;
    else (нет)
        if (Кандидат отказался?) then (да)
            -> Отказ от предложения;
            stop
        else (нет)
            -> Отказ по результатам;
            :Указать причину отказа;
            stop
        endif
    endif
else (нет)
    if (Кандидат отказался?) then (да)
        -> Отказ от предложения;
        stop
    else (нет)
        -> Интервью;
    endif
endif

:Собеседование;
if (Собеседование проведено?) then (да)
    if (Положительный результат?) then (да)
        -> Техническое задание;
    else (нет)
        if (Кандидат отказался?) then (да)
            -> Отказ от предложения;
            stop
        else (нет)
            -> Отказ по результатам;
            :Указать причину отказа;
            stop
        endif
    endif
else (нет)
    if (Кандидат отказался?) then (да)
        -> Отказ от предложения;
        stop
    else (нет)
        -> Собеседование;
    endif
endif

:Техническое задание;
if (Кандидат отказался?) then (да)
    -> Отказ от предложения;
    stop
else (нет)
    if (ТЗ выполнено и одобрено?) then (да)
        -> Принятие на работу;
        :Кандидат принят на работу;
        stop
    else (нет)
        -> Отказ по результатам;
        :Указать причину отказа;
        stop
    endif
endif

@enduml