@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' Uncomment the following line and comment the first to use locally
' !include C4_Container.puml

LAYOUT_WITH_LEGEND()

title C4 Container diagram for "Skillometer" System

Person(recruiter, "Рекрутер", "Пользователь с личным кабинетом.")
Person_Ext(applicant, "Кандидат", "Пользователь Telegram.")

System_Boundary(skillometer_system, "Система Skillometer") {
    Container(web_app, "Веб-приложение", "Интерфейс для рекрутеров")
    Container(api, "API", "Обрабатывает запросы от всех пользователей и взаимодействует с внешними системами")
    Container(db, "База данных", "PostgreSQL", "Хранит данные о вакансиях, резюме и пользователях")
    Container(notifications, "Модуль уведомлений", "Отправляет уведомления пользователям")
    Container(google_integration, "Интеграция с Google", "Интеграция с сервисами Google")
    Container(gpt_integration, "Интеграция с Chat GPT", "Обмен данными с Chat GPT для редактирования резюме")
    Container(s3_integration, "Интеграция с S3 Storage", "Хранит документы (резюме)")
    Container(user_module, "Модуль управления пользователями", "Управление пользователями и их данными")
    Container(dictionaries_module, "Модуль управления словарями", "Управление словарями данных")
    Container(vacancy_module, "Модуль управления вакансиями", "Управление вакансиями и их атрибутами")
    Container(company_module, "Модуль управления компаниями", "Управление данными о компаниях")
    Container(applicant_module, "Модуль управления кандидатами", "Управление данными о кандидатах")
    Container(reply_module, "Модуль управления откликами", "Управление откликами на вакансии")
    Container(resume_module, "Модуль управления резюме", "Управление данными о резюме")
}

System_Ext(smtp, "SMTP", "Используется для отправки уведомлений участникам процесса")
System_Ext(telegram, "Telegram", "Клиентское приложение")
System_Ext(google_calendar, "Google Calendar", "Сервис для управления расписанием и временем")
System_Ext(google_meet, "Google Meet", "Сервис для проведения видеоконференций")
System_Ext(habr, "Habr Career", "Система для получения актуальных вакансий")
System_Ext(headhunter, "HeadHunter", "Система для получения актуальных вакансий")
System_Ext(reksoft, "Reksoft", "Система ATS для получения вакансий и администрирования")
System_Ext(gpt, "Chat GPT", "ИИ для помощи в редактировании резюме")
System_Ext(s3, "S3 Storage", "Система для хранения документов (резюме)")

Rel(recruiter, web_app, "Использует")
Rel_Back(recruiter, smtp, "Отправляет письма")
Rel_Back(applicant, smtp, "Отправляет письма")
Rel_Back(notifications, smtp, "Отправляет письма")
Rel(applicant, telegram, "Использует")
Rel_Back(applicant, telegram, "Отправляет отклики")
Rel(api, google_integration, "Обмен данными")
BiRel(api, gpt_integration, "Обмен данными")
BiRel(api, s3_integration, "Обмен данными")
Rel(api, db, "Читает и записывает")
Rel(web_app, api, "Отправляет запросы")
Rel(api, telegram, "Передает данные по вакансиям")
Rel(api, user_module, "Управляет данными пользователей")
Rel(api, dictionaries_module, "Управляет словарями данных")
Rel(api, vacancy_module, "Управляет вакансиями")
Rel(api, company_module, "Управляет данными о компаниях")
Rel(api, applicant_module, "Управляет данными о кандидатах")
Rel(api, reply_module, "Управляет откликами")
Rel(api, resume_module, "Управляет резюме")
Rel(vacancy_module, dictionaries_module, "Использует для управления данными")
Rel(reply_module, vacancy_module, "Связан с")
Rel(reply_module, applicant_module, "Связан с")
Rel(resume_module, applicant_module, "Связан с кандидатами")
Rel(resume_module, dictionaries_module, "Связан с вакансиями через")
Rel(vacancy_module, habr, "Получает данные из")
Rel(vacancy_module, headhunter, "Получает данные из")
Rel(vacancy_module, reksoft, "Получает данные из")
Rel(google_integration, google_calendar, "Интеграция с")
Rel(google_integration, google_meet, "Интеграция с")
Rel(s3_integration, s3, "Интеграция с")
Rel(gpt_integration, gpt, "Интеграция с")
Rel(user_module, applicant_module, "Передает данные о пользователях")

@enduml
