apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: skillometer-db-ingress-tcp
  namespace: skillometer
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`skillometer.idev-present.com`)
      services:
        - name: postgres-postgresql
          port: 5432
  tls: {}